package com.loyaltyplatform.enums;

public enum AuditAction {
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTER,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CUSTOMER_DELETED,
    COUPON_CREATED,
    COUPON_REDEEMED,
    COUPON_EXPIRED,
    CAMPAIGN_CREATED,
    CAMPAIGN_PUBLISHED,
    CAMPAIGN_CANCELLED,
    SEGMENT_CREATED,
    SEGMENT_UPDATED,
    POINTS_EARNED,
    POINTS_REDEEMED,
    TIER_UPGRADED
}
